# Generated by Django 4.0.4 on 2022-06-10 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField()),
                ('session', models.CharField(max_length=4)),
                ('college', models.IntegerField(null=True)),
                ('department', models.IntegerField(null=True)),
                ('course', models.IntegerField(null=True)),
                ('teacher', models.IntegerField(null=True)),
                ('student', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
