# Generated by Django 4.0.6 on 2022-09-02 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.crypto import get_random_string

DEFAULT = 'abc'


def forwards(apps, _):
    ClassesModel = apps.get_model('classes', 'Classes')
    classes = ClassesModel.objects.all()

    for c in classes:
        c.code = get_random_string(14)
        c.save()


def backwards(apps, _):
    ClassesModel = apps.get_model('classes', 'Classes')
    classes = ClassesModel.objects.all()

    for c in classes:
        c.code = DEFAULT
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_alter_departmentmodel_college'),
        ('student', '0006_alter_studentmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_coursemodel_university'),
        ('college', '0013_collegemodel_logo_public_id'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classesmodel',
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes'
            },
        ),
        migrations.RenameField(
            model_name='classesmodel',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='classesmodel',
            name='session',
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='code',
            field=models.CharField(default=DEFAULT, max_length=15,
                                   unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='session_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='session_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='college',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='college.collegemodel'),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='course.coursemodel'),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='department.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='student.studentmodel'),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
