# Generated by Django 4.1.1 on 2022-09-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmodel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
        ),
    ]
