# Generated by Django 4.1.1 on 2022-09-23 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_collegemodel_logo_public_id'),
        ('department', '0010_alter_departmentmodel_college'),
        ('student', '0009_alter_studentmodel_class_rollno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_coursemodel_university'),
        ('classes', '0003_alter_classesmodel_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassesModel',
            new_name='ClassModel',
        ),
    ]
