# Generated by Django 4.1.1 on 2022-09-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_collegemodel_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0010_alter_departmentmodel_college'),
        ('course', '0007_alter_coursemodel_university'),
        ('classes', '0004_rename_classesmodel_classmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.collegemodel'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.departmentmodel'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
