# Generated by Django 4.1.1 on 2022-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_universityrollno_student_and_more'),
        ('classes', '0005_alter_classmodel_college_alter_classmodel_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='student',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='class_student', to='student.studentmodel'),
        ),
    ]
