# Generated by Django 4.0.4 on 2022-06-10 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='classes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='teacher_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
