# Generated by Django 4.0.6 on 2022-08-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_universitymodel_website'),
        ('course', '0002_coursemodel_classes_coursemodel_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='course_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='teacher_assigned',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel'),
        ),
    ]
