# Generated by Django 4.0.6 on 2022-09-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
