# Generated by Django 4.0.6 on 2022-09-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_universitymodel_website'),
        ('course', '0005_alter_coursemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel'),
        ),
    ]
