# Generated by Django 4.1.1 on 2022-09-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_universitymodel_website'),
        ('course', '0006_alter_coursemodel_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel'),
        ),
    ]
