# Generated by Django 4.0.4 on 2022-06-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.TextField()),
                ('institute_address', models.TextField()),
                ('institute_principal', models.IntegerField()),
                ('institute_logo', models.URLField()),
                ('institute_website', models.URLField()),
                ('institute_type', models.CharField(choices=[('University', 'University'), ('Autonomous College', 'Autonomous College'), ('Afflitiated UG College', 'Afflitiated UG College'), ('Affliated PG College', 'Affliated PG College'), ('Teacher Education College', 'Teacher Education College')], max_length=26)),
                ('affiliating_university', models.TextField()),
                ('institute_alias_name', models.TextField()),
                ('institute_mobile', models.CharField(max_length=15)),
                ('institute_alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('institute_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('institute_alternate_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('institute_state', models.TextField()),
                ('institute_city', models.TextField()),
                ('institute_pincode', models.CharField(max_length=10)),
                ('running_frm_own_campus', models.BooleanField(default=True)),
                ('institute_for', models.CharField(max_length=150)),
                ('location_type', models.CharField(max_length=15)),
                ('financial_model', models.CharField(max_length=50)),
                ('campus_area', models.CharField(max_length=50)),
                ('built_up_area', models.CharField(max_length=50)),
                ('minority_institution', models.BooleanField(default=False)),
                ('recognised_under_sec_2F', models.BooleanField(default=False)),
                ('recognised_under_sec_12B', models.BooleanField(default=False)),
                ('recognised_as_college_with_potential_for_excellence', models.BooleanField(default=False)),
                ('institute_mission', models.TextField(blank=True)),
                ('institute_vision', models.TextField(blank=True)),
                ('quality_policy', models.TextField(blank=True)),
                ('naac_accredited', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
    ]
