# Generated by Django 4.0.4 on 2022-06-10 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_collegemodel_institute_alternate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegemodel',
            name='affiliating_university',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='built_up_area',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='campus_area',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='financial_model',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_alternate_email',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_city',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_for',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_mission',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_pincode',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_state',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_type',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='institute_vision',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='minority_institution',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='naac_accredited',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='quality_policy',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='recognised_as_college_with_potential_for_excellence',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='recognised_under_sec_12B',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='recognised_under_sec_2F',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='running_from_own_campus',
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
