# Generated by Django 4.0.6 on 2022-08-07 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0007_SetDefaultDistrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='institute_hods',
            field=models.ManyToManyField(related_name='college', to=settings.AUTH_USER_MODEL),
        ),
    ]
