# Generated by Django 4.0.6 on 2022-08-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_collegemodel_institute_hods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_alias_name',
            new_name='alias_name',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_hods',
            new_name='hod',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_principal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='institute_website',
            new_name='website',
        ),
    ]
