# Generated by Django 4.0.6 on 2022-08-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_SetDefaultDistrict'),
        ('college', '0009_rename_institute_address_collegemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college', to='university.universitymodel'),
        ),
    ]
