# Generated by Django 4.0.6 on 2022-08-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0010_collegemodel_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemodel',
            name='principal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_principal', to=settings.AUTH_USER_MODEL),
        ),
    ]
