# Generated by Django 4.0.6 on 2022-08-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_collegemodel_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='logo_public_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
