# Generated by Django 4.1.1 on 2022-09-24 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0013_collegemodel_logo_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegemodel',
            name='teacher',
            field=models.ManyToManyField(related_name='college_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
