# Generated by Django 4.0.6 on 2022-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_AddContactModel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='district',
            field=models.CharField(choices=[('Anantnag', 'Anantnag'), ('Bandipore', 'Bandipore'), ('Baramulla', 'Baramulla'), ('Budgam', 'Budgam'), ('Doda', 'Doda'), ('Ganderbal', 'Ganderbal'), ('Jammu', 'Jammu'), ('Kathua', 'Kathua'), ('Kishtwar', 'Kishtwar'), ('Kulgam', 'Kulgam'), ('Kupwara', 'Kupwara'), ('Poonch', 'Poonch'), ('Pulwama', 'Pulwama'), ('Rajouri', 'Rajouri'), ('Ramban', 'Ramban'), ('Reasi', 'Reasi'), ('Samba', 'Samba'), ('Shopian', 'Shopian'), ('Srinagar', 'Srinagar'), ('Udhampur', 'Udhampur'), ('None of the Above', 'None of the Above')], max_length=20),
        ),
    ]
