# Generated by Django 4.0.6 on 2022-08-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmodel_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='district',
            new_name='contact_district',
        ),
    ]
