# Generated by Django 4.0.4 on 2022-06-10 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentmodel_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='classes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='courses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='department',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='phone_no',
            field=models.CharField(default=22333444, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile_image',
            field=models.URLField(default=232222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student_first_name',
            field=models.TextField(default=223334),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student_last_name',
            field=models.TextField(null=True),
        ),
    ]
