# Generated by Django 4.0.6 on 2022-08-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentmodel_batch_remove_studentmodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='district',
            field=models.CharField(blank=True, choices=[('Anantnag', 'Anantnag'), ('Bandipore', 'Bandipore'), ('Baramulla', 'Baramulla'), ('Budgam', 'Budgam'), ('Doda', 'Doda'), ('Ganderbal', 'Ganderbal'), ('Jammu', 'Jammu'), ('Kathua', 'Kathua'), ('Kishtwar', 'Kishtwar'), ('Kulgam', 'Kulgam'), ('Kupwara', 'Kupwara'), ('Poonch', 'Poonch'), ('Pulwama', 'Pulwama'), ('Rajouri', 'Rajouri'), ('Ramban', 'Ramban'), ('Reasi', 'Reasi'), ('Samba', 'Samba'), ('Shopian', 'Shopian'), ('Srinagar', 'Srinagar'), ('Udhampur', 'Udhampur')], max_length=11, null=True),
        ),
    ]
