# Generated by Django 4.0.6 on 2022-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_AddAddressAndDistrictField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='district',
            field=models.CharField(choices=[('Anantnag', 'Anantnag'), ('Bandipore', 'Bandipore'), ('Baramulla', 'Baramulla'), ('Budgam', 'Budgam'), ('Doda', 'Doda'), ('Ganderbal', 'Ganderbal'), ('Jammu', 'Jammu'), ('Kathua', 'Kathua'), ('Kishtwar', 'Kishtwar'), ('Kulgam', 'Kulgam'), ('Kupwara', 'Kupwara'), ('Poonch', 'Poonch'), ('Pulwama', 'Pulwama'), ('Rajouri', 'Rajouri'), ('Ramban', 'Ramban'), ('Reasi', 'Reasi'), ('Samba', 'Samba'), ('Shopian', 'Shopian'), ('Srinagar', 'Srinagar'), ('Udhampur', 'Udhampur')], default='Jammu', max_length=11),
        ),
    ]
