# Generated by Django 4.0.6 on 2022-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_SetDefaultDistrict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='phone_no',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_last_name',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='last_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile_image_public_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
