# Generated by Django 4.1.1 on 2022-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='university_rollno',
            field=models.IntegerField(default=19065864469481, unique=True),
        ),
    ]
