# Generated by Django 4.1.1 on 2022-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='university_rollno',
            field=models.CharField(default='89098020687204', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='class_rollno',
            field=models.CharField(default='58175451871961', max_length=50),
        ),
    ]
