# Generated by Django 4.1.1 on 2022-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentmodel_university_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_rollno',
            field=models.CharField(default='01096493059405', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university_rollno',
            field=models.CharField(default='37017683871907', max_length=50, unique=True),
        ),
    ]
