# Generated by Django 4.1.1 on 2022-09-22 12:22

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentmodel_university_rollno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='department',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not Say', 'Rather not Say')], default=student.models.random_gender, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='class_rollno',
            field=models.CharField(default='98360008414066', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university_rollno',
            field=models.CharField(default='44175165623225', max_length=50, unique=True),
        ),
    ]
