# Generated by Django 4.1.1 on 2022-09-22 15:20

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_studentmodel_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_rollno',
            field=models.CharField(default=student.models.random_rollno, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university_rollno',
            field=models.CharField(default=student.models.random_rollno, max_length=50, unique=True),
        ),
    ]
