# Generated by Django 4.1.1 on 2022-09-25 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_universitymodel_website'),
        ('college', '0014_collegemodel_teacher'),
        ('student', '0009_alter_studentmodel_class_rollno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='class_rollno',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='university_rollno',
        ),
        migrations.CreateModel(
            name='UniversityRollNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_roll_no', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='university.universitymodel')),
            ],
            options={
                'verbose_name': 'University Roll No',
                'verbose_name_plural': 'University Roll Nos',
            },
        ),
        migrations.CreateModel(
            name='CollegeRollNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_roll_no', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='college.collegemodel')),
            ],
            options={
                'verbose_name': 'College Roll No',
                'verbose_name_plural': 'College Roll Nos',
            },
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='college',
            field=models.ManyToManyField(related_name='student_college', to='student.collegerollno'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university',
            field=models.ManyToManyField(related_name='student_university', to='student.universityrollno'),
        ),
    ]
