# Generated by Django 4.1.1 on 2022-09-25 13:45

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_studentmodel_class_rollno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='university',
        ),
        migrations.AlterField(
            model_name='universityrollno',
            name='university_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_college', to='student.collegerollno'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_university', to='student.universityrollno'),
        ),
    ]
