# Generated by Django 4.1.1 on 2022-09-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_studentmodel_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegerollno',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_college_roll', to='student.studentmodel'),
        ),
        migrations.AlterField(
            model_name='universityrollno',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_university_roll', to='student.studentmodel'),
        ),
    ]
