# Generated by Django 4.1.1 on 2022-09-25 14:49

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_collegerollno_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegerollno',
            name='class_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15, unique=True),
        ),
    ]
