# Generated by Django 4.1.1 on 2022-09-25 17:23

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_studentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegerollno',
            name='class_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15),
        ),
        migrations.AlterField(
            model_name='universityrollno',
            name='university_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15),
        ),
    ]
