# Generated by Django 4.1.1 on 2022-09-27 08:51

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentmodel_class_roll_no_studentmodel_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='class_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='university_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15, unique=True),
        ),
    ]
