# Generated by Django 4.1.1 on 2022-09-27 09:20

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_studentmodel_class_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityrollno',
            name='student',
        ),
        migrations.RemoveField(
            model_name='universityrollno',
            name='university',
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='class_roll_no',
            field=models.CharField(default=student.models.random_rollno, max_length=15),
        ),
        migrations.DeleteModel(
            name='CollegeRollNo',
        ),
        migrations.DeleteModel(
            name='UniversityRollNo',
        ),
    ]
