# Generated by Django 4.0.6 on 2022-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_UniversityModelMakeNameUnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='logo_public_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='vice_chancelor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universitymodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
