# Generated by Django 4.0.4 on 2022-06-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancemodel',
            old_name='is_last',
            new_name='is_late',
        ),
    ]
