# Generated by Django 4.0.6 on 2022-09-02 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentmodel_options_and_more'),
        ('attendance', '0002_rename_is_last_attendancemodel_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='classes',
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='is_absent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student', to='student.studentmodel'),
        ),
    ]
