# Generated by Django 4.0.6 on 2022-09-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classesmodel_options_and_more'),
        ('attendance', '0003_remove_attendancemodel_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_classes', to='classes.classesmodel'),
        ),
    ]
