# Generated by Django 4.1.1 on 2022-09-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_classesmodel_classmodel'),
        ('attendance', '0005_remove_attendancemodel_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='for_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='classes.classmodel'),
        ),
    ]
