# Generated by Django 4.0.4 on 2022-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment_name', models.TextField()),
                ('department_code', models.CharField(max_length=50)),
                ('programmes_offeres', models.CharField(choices=[('Under-Graduate', 'Under-Graduate'), ('Post-Graduate', 'Post-Graduate'), ('Intergrated-PG', 'Intergrated-PG'), ('M.Phil', 'M.Phil'), ('Ph.D', 'Ph.D'), ('Certificate', 'Certificate'), ('UG Diploma', 'UG Diploma'), ('PG Diploma', 'PG Diploma')], max_length=16)),
                ('total_semesters', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=2)),
                ('student_intake', models.IntegerField()),
                ('faculty_intake', models.IntegerField()),
                ('no_of_professors', models.IntegerField()),
                ('no_of_associated_professors', models.IntegerField()),
                ('hod', models.IntegerField()),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
    ]
