# Generated by Django 4.0.5 on 2022-06-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='depatment_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='programmes_offeres',
            new_name='programmes_offered',
        ),
    ]
