# Generated by Django 4.0.4 on 2022-06-10 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_depatment_name_departmentmodel_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='faculty_intake',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='no_of_associated_professors',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='no_of_professors',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='programmes_offered',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='student_intake',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='total_semesters',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='Courses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='Teacher',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='hod',
            field=models.IntegerField(null=True),
        ),
    ]
