# Generated by Django 4.0.5 on 2022-06-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_departmentmodel_department_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Department Type',
                'verbose_name_plural': 'Department Types',
            },
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.departmenttypemodel'),
        ),
    ]
