# Generated by Django 4.0.5 on 2022-06-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_departmenttypemodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttypemodel',
            name='department_name',
            field=models.TextField(unique=True),
        ),
    ]
