# Generated by Django 4.0.5 on 2022-06-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_departmenttypemodel_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='Courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
