# Generated by Django 4.0.6 on 2022-08-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_collegemodel_logo_public_id'),
        ('department', '0009_rename_department_name_departmentmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='college.collegemodel'),
        ),
    ]
