# Districts List
DISTRICTS = [
    'Anantnag',
    'Bandipore',
    'Baramulla',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Jammu',
    'Kathua',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Poonch',
    'Pulwama',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Shopian',
    'Srinagar',
    'Udhampur',
]

# Districts Tuple
DISTRICTS_CHOICES = (
    ('Anantnag', 'Anantnag'),
    ('Bandipore', 'Bandipore'),
    ('Baramulla', 'Baramulla'),
    ('Budgam', 'Budgam'),
    ('Doda', 'Doda'),
    ('Ganderbal', 'Ganderbal'),
    ('Jammu', 'Jammu'),
    ('Kathua', 'Kathua'),
    ('Kishtwar', 'Kishtwar'),
    ('Kulgam', 'Kulgam'),
    ('Kupwara', 'Kupwara'),
    ('Poonch', 'Poonch'),
    ('Pulwama', 'Pulwama'),
    ('Rajouri', 'Rajouri'),
    ('Ramban', 'Ramban'),
    ('Reasi', 'Reasi'),
    ('Samba', 'Samba'),
    ('Shopian', 'Shopian'),
    ('Srinagar', 'Srinagar'),
    ('Udhampur', 'Udhampur'),
)
